# Generated by Django 2.2.6 on 2019-10-28 23:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_recipesearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_recipe_name', models.CharField(max_length=200)),
                ('drink_ingredients', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=10000, size=None)),
                ('drink_measurements', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=10000, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('food_ingredients', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=10000, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='weather',
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=10000, size=None),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=10000, size=None),
        ),
    ]
