# Generated by Django 2.2.6 on 2019-10-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20191028_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrecipe',
            name='drink_ingredients',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='drinkrecipe',
            name='drink_measurements',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='food_ingredients',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
